name: shellcheck

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shellcheck install.sh
        uses: ludeeus/action-shellcheck@master
        with:
          severity: warning
          scandir: './'
          additional_files: 'install.sh'
